apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nestjs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nestjs-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # Scale when CPU usage exceeds 50%