# graphql/schema.gql


type Message {
  content: String!
  type: String!
}

type Payload {
  _id: ID!
  ts: String!
  sender: String!
  message: Message!
  sent_from_ip: String
  priority: Int
}


type Query {
  getAllPayloads: [Payload!]!
  getPayloadById(id: ID!): Payload
}

type Mutation {
  addPayload(
    ts: String!
    sender: String!
    message: MessageInput!
    sent_from_ip: String
    priority: Int
  ): Boolean
}

input MessageInput {
  content: String!
  type: String!
}
